name: ${project.name}
author: LucasEmanuel
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.Main

commands:
  sgjoin:
    description: Used to join a game of SurvivalGames.
    usage: /<command> <worldname>
    permission: sgmultiverse.commands.sgjoin
  sglocation:
    description: Used to add locations to a gameworld.
    usage: /<command> <add|save|info> [<main|arena>]
    permission: sgmultiverse.commands.sglocation
  sgtp:
    description: Used to teleport between worlds.
    usage: /<command> <worldname>
    permission: sgmultiverse.commands.sgtp


permissions:
  sgmultiverse.commands.sgjoin:
    default: true
  sgmultiverse.commands.sglocation:
    default: op
  sgmultiverse.commands.sgtp:
    default: op
  sgmultiverse.ignore.startblock:
    description: Allows a user to break/place blocks before a game has started.
    default: op
  sgmultiverse.ignore.blockfilter:
    description: Allows a user to bypass the blockfilter.
    default: false